config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :jobs
	root 'jobs#index'

	 devise_scope :user do
	 	get '/users/sign_out' => 'devise/sessions#destroy'

    authenticated :user do
      root :to => 'jobs#index'
    end
    unauthenticated :user do
      root :to => 'jobs#index', as: :unauthenticated_root
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :category
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :authenticate_user!, :except => [:index, :show]
	before_action :find_job, only: [:show, :edit, :update, :destroy]
	
	def index
		if params[:category].blank?
			@jobs = Job.all.order('created_at DESC')
		else
			@category_id = Category.find_by(name: params[:category]).id
			@jobs = Job.where(category_id: @category_id)
		end
	end
	
	def show
		
	end
	
	def new
		@job = Job.new 
	end
	
	def create
		@job = Job.new(jobs_params)
		if @job.save
			redirect_to @job
		else
			render "new"
		end
	end
	
	def edit
		
	end
	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "edit"
		end
	end
	
	def destroy
		@job.destroy
		redirect_to root_path	
	end
	private
	def jobs_params
		params.require(:job).permit(:title, :description, :url, :company, :category_id, :user_id)

	end
	
	def find_job
		@job = Job.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
=simple_form_for(@job, html: {class: 'form-horizontal'}) do |f|
	=f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"}
	=f.input :title, label: "Job Title"
	=f.input :description, label: "Description"
	=f.input :company, label: "Your Company"
	=f.input :url, label: "Link to the Job"
	=f.hidden_field :user_id, :value => current_user.id
	%br/
	=f.button :submit

app/views/jobs/edit.html.haml
%h1 Edit Job
=render 'form'
=link_to 'Back', @job

app/views/jobs/index.html.haml
-@jobs.each do |job|
	%h2= link_to job.title, job
	%p= job.company

app/views/jobs/new.html.haml
%h1 New Job
=render 'form'
=link_to 'Back', root_path

app/views/jobs/show.html.haml
%h1= @job.title
%p= @job.description
%p= @job.company

=link_to "Home", root_path
-if @job.user == current_user
	=link_to "Edit", edit_job_path(@job)
	=link_to "Delete", job_path(@job), method: :delete, data: {confirm: "Are you sure?"} 

app/views/layouts/application.html.haml
%html
%head
%title Surf Jobs
=csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand JOB SURF
			%ul.nav.navbar-nav
				%li= link_to "All Jobs", root_path
				-Category.all.each do |category|
					%li= link_to category.name, jobs_path(category: category.name)
				%li= link_to "Post New Job", new_job_path
				
				-if current_user.present?
					%li= link_to "Logout", destroy_user_session_path
				-else
					%li= link_to "Signup", new_user_registration_path
					%li= link_to "Login", new_user_session_path

	.container
		.notice= notice 
		.alert= alert
		=yield







  